# frozen_string_literal: true

source "https://rubygems.org"

# source "file:///path/to/gems"


gem "log4r", "~> 1.1"

gem "test-unit", "~> 3.6"

gem "activerecord", "= 6.1.7.10"

gem "rexml", "= 3.4.0"

gem "curb", "= 1.3.1"

gem "sqlite3", "= 1.7.3"

gem "nokogiri", "= 1.17.2"

gem "bcrypt", "= 3.1.22"

gem "bcrypt_pbkdf", "= 1.1.2"

gem "bigdecimal", "= 4.1.2"

gem "dotenv", "~> 2.8"

gem "ffi", "~> 1"

gem "filesize", "~> 0.1"

gem "ftools", "~> 0.0.0"

gem "ftpfxp", "~> 0.0.4"

gem "shell", "~> 0.8.1"

gem "manpages", "~> 0.7.0"

gem "nats", "~> 0.11.0"

gem "nats-pure", "~> 2.5"

gem "net-ftp", "~> 0.3.9"

gem "net-sftp", "~> 4.0"

gem "net-ssh", "~> 7.3"

gem "net-smtp", "~> 0.5.1"

gem "net-pop", "~> 0.1.2"

gem "roman-numerals", "~> 0.3.0"

gem "ed25519", "~> 1.4"

gem "minitest", "~> 5.25"

gem "sys-filesystem", "~> 1.6"

gem "getoptlong", "~> 0.2.1"

gem "mutex_m", "~> 0.3.0"
