version: "3"
services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_DB: "dec_db_s2"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
