##
## DOCKER COMPOSE DEC / MINARC SERVICE
## 
## docker exec -it dec_db_s2 psql -U postgres -c "create database dec_db_s2"
##
## Docker POSTGRES reference environment variables & initdb reference
## https://hub.docker.com/_/postgres
##
## https://www.postgresql.org/docs/9.2/auth-pg-hba-conf.html
## https://github.com/docker-library/postgres/issues/482
## host all all 0.0.0.0/0 trust
## 
## Docker Networking
## https://docs.docker.com/compose/networking/
##
## Docker Volumes
## https://docs.docker.com/compose/compose-file/#volumes
##
## Create a named volume beforehand
## https://stackoverflow.com/questions/52152231/how-to-mount-docker-directory-into-host-directory-with-docker-compose
##
## network mode host for FTP
## https://docs.docker.com/compose/compose-file/#network_mode
##
## network_mode: "host"
##
## https://docs.docker.com/compose/compose-file/#network-configuration-reference
##
##
## > s2decservices
## - rake -f build_minarc.rake minarc:install[s2decservice,e2espm-inputhub]
##
##
version: '3'

services:
  minarc_db_s2:
     image: "postgres:11"
     container_name: minarc_db_s2
     restart: always
     environment:
        POSTGRES_DB: "e2edc"
        POSTGRES_USER: "e2edc"
        POSTGRES_PASSWORD: "e2edc"
        POSTGRES_HOST_AUTH_METHOD: "trust"
     ports:
      - "5432:5432"
     volumes:
      - /Volumes/dec/minarc_db:/var/lib/postgresql/data
  minarc_s2:
      depends_on:
         - "minarc_db_s2"
      image: app_minarc_s2
      container_name: minarc_s2
      ports:
      - "4567:4567"
      restart: always
      volumes:
        - /Volumes/dec:/volumes/dec
  dec_s2:
      depends_on:
         - "minarc_db_s2"
      image: app_dec_s2
      container_name: dec_s2
      restart: always
      volumes:
        - /Volumes/dec:/volumes/dec
