#!/usr/bin/env ruby

require 'rubygems'
require 'test/unit'
require 'fileutils'
require 'date'

require 'cuc/Log4rLoggerFactory'
require 'cuc/DirUtils'

require 'dec/DEC_Environment'
require 'dec/ReadConfigDEC'

# Preconditions:
# 1 - setup 
# 2 - teardown

# Select a single test of the suite
# ruby decTestInterface_OData_CDSE -n test_my_method 


class DECTestInterfaceCDSE < Test::Unit::TestCase

   include CUC::DirUtils
   include DEC

   
   # Order of the test cases execution according to defintion within code
   #self.test_order = :defined
   
      
   ## ------------------------------------------------------
   
   Test::Unit.at_start do      
   #def setup
      @my_argv = ARGV.dup
      puts
      puts "======================================"
      puts "DEC ODATA Interface Test Cases #{self.class.name.split('::').last}"
      puts
      puts
      puts "DO NOT EXECUTE IN THE PRODUCTION ENVIRONMENT !!!!!"
      puts
      puts "or with operational data in the archive"
      puts
      puts "THINK CAREFULLY !!! "
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      bBatchmode = false
            
      @my_argv.each{|arg|
         if arg == "batchmode" then
            puts "batch mode execution on"
            bBatchmode = true
            break
         end
      }
       
      if bBatchmode == false then
         c = STDIN.getc
         if c != 'Y' then
            exit(99)
         end
      end   
      
      @@conf = DEC_Environment.new
      
      @@conf.wrapper_load_config
        
      @@conf.wrapper_print_environment
      
      @@conf.createEnvironmentDirs

      if @@conf.wrapper_check_environment == false then
         puts "DEC environment not suited for unit tests"
         puts
         exit(99)
      end

      # initialize logger
      loggerFactory = CUC::Log4rLoggerFactory.new("test", "#{ENV['DEC_CONFIG']}/dec_log_config.xml")
      if @isDebugMode then
         loggerFactory.setDebugMode
      end
      @@logger = loggerFactory.getLogger
      
      if @@logger == nil then
         puts
		   puts "Error in decUnitTests::main"
		   puts "Could not set up logging system !  :-("
         puts "Check DEC logs configuration under \"#{ENV['DEC_CONFIG']}/dec_log_config.xml\"" 
		   puts
		   puts
		   exit(99)
      end

      
   end
   
   ## ------------------------------------------------------

   Test::Unit.at_exit do
      puts "End of DEC tests 4 DHUS"
   end

   def setup
      puts "setup"
   end

   def teardown
      puts "teardown"
   end

   ## ------------------------------------------------------



   ## -------------------------------------------------------------

   def test_commandline_helpers
      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s} START")

      cmd = "decODataClient -v"
      
      @@logger.debug("#{cmd}")
      assert(system(cmd), cmd)

      cmd = "decODataClient -h"
      @@logger.debug("#{cmd}")
      assert(system(cmd), cmd)

      cmd = "decODataClient -u mario -p cipollini"
      @@logger.debug("#{cmd}")
      assert(!system(cmd), "#{cmd} invoked without the query")

      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s} END")
   end

   ## ------------------------------------------------------

   def test_S3_OL_1_ERR
      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s}")
      ## Query by Mission collection and product type for Sentinel-3 OL_1_ERR___
      cmd = "decODataClient --query cdse:s3:OL_1_ERR___  --time #{Date.today.to_datetime.strftime("%Y-%m-%dT%H:%M:%S.000Z")}"
      @@logger.debug("#{cmd}")
      assert(system(cmd), "#{cmd} cdse:s3:OL_1_ERR___ with datetime")
   end

   def test_S3A_OL_1_EFR
      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s}")
      ## Query by Mission collection and product type for Sentinel-3 OL_1_EFR___
      cmd = "decODataClient --query cdse:s3a:OL_1_EFR___  --time #{Date.today.to_datetime.strftime("%Y-%m-%dT%H:%M:%S.000Z")}"
      @@logger.debug("#{cmd}")
      assert(system(cmd), "#{cmd} cdse:s3a:OL_1_EFR___ with datetime")
   end

   def test_S3A_NR_OL_1_EFR
      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s}")
      ## Query by Mission collection and product type for Sentinel-3 OL_1_EFR___
      cmd = "decODataClient --query cdse:s3a:NR_OL_1_EFR___  --time #{Date.today.to_datetime.strftime("%Y-%m-%dT%H:%M:%S.000Z")}"
      @@logger.debug("#{cmd}")
      assert(system(cmd), "#{cmd} cdse:s3a:NR_OL_1_EFR___ with datetime")
   end

   def test_S3_OL_1_EFR
      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s}")
      ## Query by Mission collection and product type for Sentinel-3 OL_1_EFR___
      cmd = "decODataClient --query cdse:s3:OL_1_EFR___  --time #{Date.today.to_datetime.strftime("%Y-%m-%dT%H:%M:%S.000Z")}"
      @@logger.debug("#{cmd}")
      assert(system(cmd), "#{cmd} cdse:s3:OL_1_EFR___ with datetime")
   end

   def test_S3_SL_1_RBT
      @@logger.debug("#{self.class.name.split('::').last}::#{__method__.to_s}")
      ## Query by Mission collection and product type for Sentinel-3 OL_1_ERR___
      cmd = "decODataClient --query cdse:s3:SL_1_RBT___  --time #{Date.today.to_datetime.strftime("%Y-%m-%dT%H:%M:%S.000Z")}"
      @@logger.debug("#{cmd}")
      assert(system(cmd), "#{cmd} cdse:s3:SL_1_RBT___ with datetime")
   end

end


## ===================================================================




