#!/usr/bin/env ruby -W0

require 'rubygems'
require 'test/unit'
require 'fileutils'
require 'date'

require 'cuc/Log4rLoggerFactory'
require 'cuc/DirUtils'

require 'dec/DEC_Environment'
require 'dec/ReadConfigDEC'

# The following configurations support this test interface:
# > rake -f build_dec.rake dec:install[adgs,localhost,adgs_test_pg]

# > testTEC

class DECTestInterface_NASA_CDDIS_HTTPS < Test::Unit::TestCase

   include CUC::DirUtils
   include DEC

   
   # Order of the test cases execution according to defintion within code
   #self.test_order = :defined
      
   ## ------------------------------------------------------
   
   Test::Unit.at_start do
      @my_argv = ARGV.dup
      puts
      puts "======================================"
      puts "DEC NASA Interface Test Cases #{self.class.name.split('::').last}"
      puts
      puts
      puts "DO NOT EXECUTE IN THE PRODUCTION ENVIRONMENT !!!!!"
      puts
      puts "or with operational data in the archive"
      puts
      puts "THINK CAREFULLY !!! "
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      bBatchmode = false
            
      @my_argv.each{|arg|
         if arg == "batchmode" then
            puts "batch mode execution on"
            bBatchmode = true
            break
         end
      }
       
      if bBatchmode == false then
         c = STDIN.getc
         if c != 'Y' then
            exit(99)
         end
      end   
      
      cmd = "mkdir -p /tmp/adgs/dec/log"
      system(cmd)
      system("mkdir -p /tmp/adgs/tmp/in_basket_if_s1_cddis_4_aux_tec")

      @@conf = DEC_Environment.new

      @@conf.wrapper_load_config

      @decConfigDir = ENV['DEC_CONFIG']
 
      ## ----------------------------------
      ## initialize logger
      loggerFactory = CUC::Log4rLoggerFactory.new("test", "#{@decConfigDir}/dec_log_config.xml")
   
      @@logger = loggerFactory.getLogger   
      if @@logger == nil then
         puts
		   puts "Error in #{File.basename(__FILE__)}"
     	   puts "Could not initialize logging system !  :-("
         puts "Check DEC logs configuration under \"#{@decConfigDir}/orchestrator_log_config.xml\"" 
 	      puts
   	   exit(99)
      end

      ## ----------------------------------
      @@conf.wrapper_unset_config

  
     

      @@logger.info("NASA CDDIS with HTTPS interface tests")
      
   end
   
   ## ------------------------------------------------------

   Test::Unit.at_exit do
      @@logger.info("End of DEC tests #{File.basename(__FILE__)}")
   end

   ## ------------------------------------------------------

   def setup
      @@logger.info("#{File.basename(__FILE__)}::#{__method__.to_s}")
      
      decConfig   = DEC::ReadConfigDEC.instance
      reportDir   = decConfig.getReportDir

      system("\\rm -rf #{reportDir}")
      # system("\\rm -rf /tmp/dec*")
      system("\\rm -rf /tmp/adgs/dec/log/ADGS*.log")
      system("\\rm -rf /tmp/adgs/tmp/in_basket_if_s1_cddis_4_aux_tec/JPL*")

      cmd = "mkdir -p /tmp/dec/int/"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "decManageDB -d"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decManageDB -c"
      @@logger.debug(cmd)
      ret = system(cmd)
      
      cmd = "decConfigInterface2DB -a S1_CDDIS_4_AUX_TEC_HTTPS"
      @@logger.debug(cmd)
      ret = system(cmd)

   end

   ## -----------------------------------------------------------

   def teardown      
      @@logger.info("#{File.basename(__FILE__)}::#{__method__.to_s}")
   end

   ## -----------------------------------------------------------

   def testTEC
      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} START")
   
      # cmd = "decCheckConfig -e S1_CDDIS_4_AUX_TEC_HTTPS"
      # @@logger.info(cmd)
      # assert(system(cmd), "check config of S1_CDDIS_4_AUX_TEC_HTTPS")  

      cmd = "decGetFromInterface -m S1_CDDIS_4_AUX_TEC_HTTPS -l"
      @@logger.info(cmd)
      assert(system(cmd), "list from S1_CDDIS_4_AUX_TEC_HTTPS")

      cmd = "decGetFromInterface -m S1_CDDIS_4_AUX_TEC_HTTPS"
      @@logger.info(cmd)
      assert(system(cmd), "pull from S1_CDDIS_4_AUX_TEC_HTTPS")

      cmd = "decGetFromInterface -m S1_CDDIS_4_AUX_TEC_HTTPS"
      @@logger.info(cmd)
      assert(system(cmd), "duplicated pull from S1_CDDIS_4_AUX_TEC_HTTPS")

      arr = Dir["/tmp/adgs/dec/log/ADGS*.log"]
      # arr = Dir["/data/mocExternalInterfaces/log/DEC*.log"]
      cmd = "grep ERROR #{arr[0]}"
      assert(!system(cmd), "ERROR found in DEC logs in #{__method__.to_s}") 

      @@logger.debug("Verification of log trace: file pull")
      cmd = "grep DEC\_110 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "Pull mission traced in DEC logs in #{__method__.to_s}") 

      @@logger.debug("Verification of log trace: file pull")
      cmd = "grep DEC\_301 #{arr[0]}"
      @@logger.debug(cmd)
      assert(system(cmd), "Pull mission traced in DEC logs in #{__method__.to_s}") 

      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} END")
   end

   ## -----------------------------------------------------------
   


end

## ===================================================================




