#!/usr/bin/env ruby -W0

require 'rubygems'
require 'test/unit'
require 'fileutils'

require 'cuc/DirUtils'
require 'cuc/Log4rLoggerFactory'

require 'dec/DEC_Environment'
require 'dec/ReadConfigDEC'
require 'dec/ReadConfigOutgoing'
require 'dec/ReadConfigIncoming'

## rake -f build_dec.rake dec:install[dectest,localhost,s2_test_pg]

=begin
docker run \
    -v <host-dir>/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key \
    -v <host-dir>/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key \
    -v <host-dir>/share:/home/foo/share \
    -p 2222:22 -d atmoz/sftp \
    foo::1001
=end


class DECTestCase_SFTP < Test::Unit::TestCase

   include Test::Unit::Data
   
   include CUC::DirUtils
   
   include DEC
         
   # Order of the test cases execution according to definition within code
   self.test_order = :defined
   
   @my_argv = ARGV.dup
   # --------------------------------------------------------
   
   Test::Unit.at_start do

      system("clear")
      puts
      puts "======================================"
      puts "DEC #{File.basename(__FILE__)} Unit Test Cases"
      puts
      puts
      
      @@conf = DEC_Environment.new

      @@conf.wrapper_load_config

      @decConfigDir = ENV['DEC_CONFIG']
 
      ## ----------------------------------
      ## initialize logger
      loggerFactory = CUC::Log4rLoggerFactory.new("DECTEST", "#{@decConfigDir}/dec_log_config.xml")
   
      @@logger = loggerFactory.getLogger   
      if @@logger == nil then
         puts
		   puts "Error in #{File.basename(__FILE__)}"
     	   puts "Could not initialize logging system !  :-("
         puts "Check DEC logs configuration under \"#{@decConfigDir}/orchestrator_log_config.xml\"" 
 	      puts
   	   exit(99)
      end

      system("clear")
      puts
      puts "======================================"
      puts "DEC #{File.basename(__FILE__)} Unit Test Cases"
      puts
      puts
      puts "DO NOT EXECUTE IN THE PRODUCTION ENVIRONMENT !!!!!"
      puts
      puts "or with operational data in the archive"
      puts
      puts "THINK CAREFULLY !!! "
      puts
      puts "Execute the following test environment:"
      puts "docker run --name dec_sftp_server -v /tmp/tmp:/home/test_sftp -v ~/.ssh/id_rsa.pub:/home/test_sftp/.ssh/keys/id_rsa.pub:ro -p 2222:22 -d atmoz/sftp test_sftp::1000"
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      bBatchmode = false
            
      @my_argv.each{|arg|
         if arg == "batchmode" then
            puts "batch mode execution on"
            bBatchmode = true
            break
         end
      }
       
      if bBatchmode == false then
         c = STDIN.getc
         if c != 'Y' then
            exit(99)
         end
      end   

      cmd = "docker container stop dec_sftp_server"
      @@logger.info(cmd)
      system(cmd)
      sleep(10.0)

      cmd = "docker container rm dec_sftp_server"
      @@logger.info(cmd)
      system(cmd)
      sleep(10.0)

      # Delete the known host entry associated to previous container executions
      cmd = "rm -f ~/.ssh/id_rsa*"
      @@logger.debug(cmd)
      system(cmd)

       # Delete the known host entry associated to previous container executions
      cmd = "ssh-keygen -q -t rsa -b 4096 -f ~/.ssh/id_rsa < /dev/null"
      @@logger.debug(cmd)
      system(cmd)

      # Delete the known host entry associated to previous container executions
      cmd = "ssh-keygen -f ~/.ssh/known_hosts -R '[localhost]:2222'"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -rf /tmp/tmp"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "mkdir -p /tmp/tmp/dir1"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "mkdir -p /tmp/tmp/dir2"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "mkdir -p /tmp/dec/in_basket_if_localhost_secure_keys"
      system(cmd)

      cmd = "mkdir -p /tmp/tmp/dec/in_basket_if_localhost_secure_keys"
      system(cmd)

      cmd = "mkdir -p /tmp/tmp/dec_simul_if/localhost_secure_keys/download"
      system(cmd)

      cmd = "mkdir -p /tmp/tmp/dec_simul_if/localhost_secure_keys/upload/_TEMP_"
      system(cmd)

      conf = ReadConfigOutgoing.instance

      dir = conf.getOutgoingDir("LOCALHOST_SECURE_KEYS")
      @@logger.debug("checking #{dir}")
      # checkDirectory(dir)

      dir = conf.getUploadDir("LOCALHOST_SECURE_KEYS")
      @@logger.debug("checking #{dir}")
      # checkDirectory(dir)

      dir = conf.getUploadTemp("LOCALHOST_SECURE_KEYS")
      @@logger.debug("checking #{dir}")
      # checkDirectory(dir)

      conf = ReadConfigIncoming.instance

      dir = conf.getIncomingDir("LOCALHOST_SECURE_KEYS")
      @@logger.debug("checking #{dir}")
      # checkDirectory(dir)

      arr = conf.getDownloadDirs("LOCALHOST_SECURE_KEYS")

      arr.each{|inconfig|
         @@logger.debug("checking #{inconfig[:directory]}")
         # checkDirectory(inconfig[:directory])
      }

      ## ----------------------------------
      @@conf.wrapper_unset_config
   
      # ---------------------
      # delete all log files
      cmd = "rm -f /tmp/test_pull_sftp*.log"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/test_push_sftp*.log"
      @@logger.debug(cmd)
      system(cmd)      
      # ---------------------

      ## -----------------------------------------
      ## list mode and subsequent download
      
      downloadDir = "/tmp/tmp/dec_simul_if/localhost_secure_keys/download"
      @@numFiles    = 4
      numBlocks   = 1024000

      1.upto(@@numFiles) do |i|
         filename = "test_sftp_#{i}.bin"
         cmd = "dd if=/dev/urandom of=#{downloadDir}/#{filename} bs=1024 count=#{numBlocks}"
         @@logger.debug(cmd)
         system(cmd)
      end

      cmd = "docker run --name dec_sftp_server -v /tmp/tmp:/home/test_sftp -v ~/.ssh/id_rsa.pub:/home/test_sftp/.ssh/keys/id_rsa.pub:ro -p 2222:22 -d atmoz/sftp test_sftp::1000"
      @@logger.info(cmd)
      system(cmd)
      sleep(10.0)

   end
   
   ## --------------------------------------------------------
   
   Test::Unit.at_exit do
      @@logger.info("End of DEC tests #{File.basename(__FILE__)}")
   end
   ## --------------------------------------------------------   
   
   # Setup before every test-case
   #
   def setup
      @@logger.info("#{File.basename(__FILE__)}::#{__method__.to_s} START")
      

      @@logger.debug("Defining environment variable used in configuration: DEC_TMP")
      ENV['DEC_TMP'] = '/tmp'

      cmd = "decManageDB -d"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decManageDB -c"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decConfigInterface2DB -a LOCALHOST_SECURE_KEYS"
      @@logger.debug(cmd)
      ret = system(cmd)

      @@logger.info("#{File.basename(__FILE__)}::#{__method__.to_s} END")
   
      cmd = "rm -f /tmp/DEC*.log"
      @@logger.debug(cmd)
      system(cmd)

   end
   ## ------------------------------------------------------
   ## After every test case

   def teardown
      return
   end
   ## ------------------------------------------------------
   
   ## ------------------------------------------------------
   
   ##
   
   # data("SEPARATOR",     ["TEST LABEL",     0,   0,   0,    false])
   # data("0",     ["1_files_1GB_1Slots",      1,   1024000,   1,     false])
   # data("1",     ["3_files_1GB_1Slots",      3,   1024000,   1,     false])
   # data("2",     ["3_files_1GB_3Slots",      3,   1024000,   3,     false])
   # data("3",     ["7_files_1GB_5Slots",      7,   1024000,   5,     false])
   data("4",     ["10_files_1GB_5Slots",     10,  1024000,   5,     false])

   ## PULL Circulations
   def test_pull(params)

      label, numFiles, numBlocks, numSlots, noDB = params

      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} START #{label}")
 
=begin
      checkDirectory("/tmp/tmp/dec/in_basket_if_localhost_secure")
      checkDirectory("/tmp/tmp/dec_simul_if/localhost_secure/download")
      checkDirectory("/tmp/tmp/dec_simul_if/localhost_secure/upload/_TEMP_")
=end

      cmd = "\\rm -rf /tmp/tmp/dec/in_basket_if_localhost_secure_keys/*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "decManageDB -d"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decManageDB -c"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decConfigInterface2DB -a LOCALHOST_SECURE_KEYS"
      @@logger.debug(cmd)
      ret = system(cmd)

      cmd = "decValidateConfig -a"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)   
   
      cmd = "decCheckConfig -e LOCALHOST_SECURE_KEYS"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      
           
      cmd = "decGetFromInterface -m LOCALHOST_SECURE_KEYS -l"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      
      cmd = "decGetFromInterface -m LOCALHOST_SECURE_KEYS -P #{numSlots}"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      arrFiles = Dir["/tmp/dec/in_basket_if_localhost_secure_keys/test_sftp*"]      
      assert(arrFiles.length == @@numFiles, "Number of files pulled")
      
      cmd = "decStats -H 1"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      ## -----------------------------------------
      
      arr = Dir["/tmp/DEC*.log"]

      cmd = "cp #{arr[0]} /tmp/test_pull_sftp_#{label}.log"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "grep stats /tmp/test_pull_sftp*.log"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "grep DEC\_110 /tmp/test_pull_sftp*.log"
      @@logger.debug(cmd)
      system(cmd)

      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} END #{label}")
   end
   ## ------------------------------------------------------

   ## ------------------------------------------------------
   
   # data("SEPARATOR",     ["Start of the Test",     0,   0,   0,    false])
   # data("0",     ["1_files_1GB_1Slots_NoDB",      1,   1024000,   1,     true])
   # data("1",     ["3_files_1GB_1Slots_NoDB",      3,   1024000,   1,     true])
   data("2",     ["7_files_1GB_1Slots_NoDB",      7,   1024000,   1,     true])

   ## PUSH Circulations
   def test_push(params)

      label, numFiles, numBlocks, numSlots, noDB = params

      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} START #{label}")

      checkDirectory("/tmp/dec/in_basket_if_LOCALHOST_SECURE_KEYS/")
      system("\\rm -rf /tmp/dec/in_basket_if_LOCALHOST_SECURE_KEYS/*")

      outTray     = "/tmp/dec_delivery_root"
      checkDirectory(outTray)

      1.upto(numFiles) do |i|
         filename = "test_sftp_#{i}.bin"
         cmd = "dd if=/dev/urandom of=#{outTray}/#{filename} bs=1024 count=#{numBlocks}"
         @@logger.debug(cmd)
         system(cmd)
      end


      cmd = "decValidateConfig -a"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)   
   
      cmd = "decCheckConfig -e LOCALHOST_SECURE_KEYS"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
      
      checkDirectory("/tmp/dec_delivery_root/GIP_PROBA2")
      
      sourceDir = DEC::ReadConfigDEC.instance.getSourceDir
      
      checkDirectory(sourceDir)
      @@logger.debug("SOURCE DIR => #{sourceDir}")

      cmd = "decGetFiles4Transfer"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      cmd = "decSend2Interface --mnemonic LOCALHOST_SECURE_KEYS -O"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

#      cmd = "decDeliverFiles -D"
#      puts cmd
#      assert(system(cmd), cmd)

      cmd = "decListDirUpload -m LOCALHOST_SECURE_KEYS -t"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
    
      cmd = "decStats"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      arr = Dir["/tmp/DEC*.log"]
     
      cmd = "cp #{arr[0]} /tmp/test_push_sftp_#{label}.log"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/dec_simul_if/localhost_secure_keys/upload/test_sftp_*.bin"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      @@logger.info("#{self.class.name.split('::').last}::#{__method__.to_s} END")

   end
   ## ------------------------------------------------------



end

### ==================================================================
